import json
import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d 
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.cm as cm
import numpy as np


with open('D:\\郝千越文件\\其他\\SRT\\疫情传播建模\\data_beijing_region\\processed\\dense_region.json','r') as f:
    dense=json.load(f)
with open('D:\\郝千越文件\\其他\\SRT\\疫情传播建模\\data_beijing_region\\processed\\flow_region.json','r') as f:
    flow=json.load(f)
with open('D:\\郝千越文件\\其他\\SRT\\疫情传播建模\\result\\experiment7\\不同区域发展速度\\peak_date_region-1.json','r') as f:
    date=json.load(f)
with open('D:\\郝千越文件\\其他\\SRT\\疫情传播建模\\result\\experiment7\\不同区域发展速度\\peak_height_region-1.json','r') as f:
    height=json.load(f)
with open('D:\\郝千越文件\\其他\\SRT\\疫情传播建模\\result\\experiment7\\不同区域发展速度\\acc_region-1.json','r') as f:
    acc=json.load(f)
with open('D:\\郝千越文件\\其他\\SRT\\疫情传播建模\\result\\experiment7\\不同区域发展速度\\peak_date_region-150start.json','r') as f:
    date150=json.load(f)
with open('D:\\郝千越文件\\其他\\SRT\\疫情传播建模\\result\\experiment7\\不同区域发展速度\\peak_height_region-150start.json','r') as f:
    height150=json.load(f)
with open('D:\\郝千越文件\\其他\\SRT\\疫情传播建模\\result\\experiment7\\不同区域发展速度\\acc_region-150start.json','r') as f:
    acc150=json.load(f)
with open('D:\\郝千越文件\\其他\\SRT\\疫情传播建模\\result\\experiment7\\不同区域发展速度\\peak_date_region-300start.json','r') as f:
    date300=json.load(f)
with open('D:\\郝千越文件\\其他\\SRT\\疫情传播建模\\result\\experiment7\\不同区域发展速度\\peak_height_region-300start.json','r') as f:
    height300=json.load(f)
with open('D:\\郝千越文件\\其他\\SRT\\疫情传播建模\\result\\experiment7\\不同区域发展速度\\acc_region-300start.json','r') as f:
    acc300=json.load(f)
with open('D:\\郝千越文件\\其他\\SRT\\疫情传播建模\\result\\experiment7\\不同区域发展速度\\peak_date_region-500start.json','r') as f:
    date500=json.load(f)
with open('D:\\郝千越文件\\其他\\SRT\\疫情传播建模\\result\\experiment7\\不同区域发展速度\\peak_height_region-500start.json','r') as f:
    height500=json.load(f)
with open('D:\\郝千越文件\\其他\\SRT\\疫情传播建模\\result\\experiment7\\不同区域发展速度\\acc_region-500start.json','r') as f:
    acc500=json.load(f)

dense=np.array(dense)
flow=np.array(flow)
date=np.array(date)
date=date/48
date150=np.array(date150)
date150=date150/48
date300=np.array(date300)
date300=date300/48
date500=np.array(date500)
date500=date500/48

plt.subplot(2,2,1)
plt.scatter(dense,date,c=date,marker='o',cmap=cm.Reds_r,label='50start',vmin=110,vmax=152)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Population density(people/km^2)')
plt.ylabel('Peak-date(day)',fontsize=15)
plt.ylim(110,152)
plt.subplot(2,2,2)
plt.scatter(dense,date150,c=date150,marker='o',cmap=cm.Reds_r,label='150start',vmin=110,vmax=152)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Population density(people/km^2)')
plt.ylabel('Peak-date(day)',fontsize=15)
plt.ylim(110,152)
plt.subplot(2,2,3)
plt.scatter(dense,date300,c=date300,marker='o',cmap=cm.Reds_r,label='300start',vmin=110,vmax=152)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Population density(people/km^2)')
plt.ylabel('Peak-date(day)',fontsize=15)
plt.ylim(110,152)
plt.subplot(2,2,4)
plt.scatter(dense,date500,c=date500,marker='o',cmap=cm.Reds_r,label='500start',vmin=110,vmax=152)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Population density(people/km^2)')
plt.ylabel('Peak-date(day)',fontsize=15)
plt.ylim(110,152)
plt.suptitle('Population density & Peak-date',fontsize=15)
plt.show()

plt.subplot(2,2,1)
plt.scatter(flow,date,c=date,marker='o',cmap=cm.Reds_r,label='50start',vmin=110,vmax=152)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Relatively flow',fontsize=15)
plt.ylabel('Peak-date(day)',fontsize=15)
plt.ylim(110,152)
plt.subplot(2,2,2)
plt.scatter(flow,date150,c=date150,marker='o',cmap=cm.Reds_r,label='150start',vmin=110,vmax=152)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Relatively flow',fontsize=15)
plt.ylabel('Peak-date(day)',fontsize=15)
plt.ylim(110,152)
plt.subplot(2,2,3)
plt.scatter(flow,date300,c=date300,marker='o',cmap=cm.Reds_r,label='300start',vmin=110,vmax=152)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Relatively flow',fontsize=15)
plt.ylabel('Peak-date(day)',fontsize=15)
plt.ylim(110,152)
plt.subplot(2,2,4)
plt.scatter(flow,date500,c=date500,marker='o',cmap=cm.Reds_r,label='500start',vmin=110,vmax=152)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Relatively flow',fontsize=15)
plt.ylabel('Peak-date(day)',fontsize=15)
plt.ylim(110,152)
plt.suptitle('Population mobility & Peak-date',fontsize=15)
plt.show()

plt.subplot(2,2,1)
plt.scatter(dense,height,c=height,marker='o',cmap=cm.Reds,label='50start',vmin=20,vmax=30)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Population density(people/km^2)',fontsize=15)
plt.ylabel('Peak-height(%)',fontsize=15)
plt.ylim(20,30)
plt.subplot(2,2,2)
plt.scatter(dense,height150,c=height150,marker='o',cmap=cm.Reds,label='150start',vmin=20,vmax=30)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Population density(people/km^2)',fontsize=15)
plt.ylabel('Peak-height(%)',fontsize=15)
plt.ylim(20,30)
plt.subplot(2,2,3)
plt.scatter(dense,height300,c=height300,marker='o',cmap=cm.Reds,label='300start',vmin=20,vmax=30)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Population density(people/km^2)',fontsize=15)
plt.ylabel('Peak-height(%)',fontsize=15)
plt.ylim(20,30)
plt.subplot(2,2,4)
plt.scatter(dense,height500,c=height500,marker='o',cmap=cm.Reds,label='500start',vmin=20,vmax=30)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Population density(people/km^2)',fontsize=15)
plt.ylabel('Peak-height(%)',fontsize=15)
plt.ylim(20,30)
plt.suptitle('Population density & Peak-height',fontsize=15)
plt.show()

plt.subplot(2,2,1)
plt.scatter(flow,height,c=height,marker='o',cmap=cm.Reds,label='50start',vmin=20,vmax=28)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Relatively flow',fontsize=15)
plt.ylabel('Peak-height(%)',fontsize=15)
plt.ylim(20,28)
plt.subplot(2,2,2)
plt.scatter(flow,height150,c=height150,marker='o',cmap=cm.Reds,label='150start',vmin=20,vmax=28)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Relatively flow',fontsize=15)
plt.ylabel('Peak-height(%)',fontsize=15)
plt.ylim(20,28)
plt.subplot(2,2,3)
plt.scatter(flow,height300,c=height300,marker='o',cmap=cm.Reds,label='300start',vmin=20,vmax=28)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Relatively flow',fontsize=15)
plt.ylabel('Peak-height(%)',fontsize=15)
plt.ylim(20,28)
plt.subplot(2,2,4)
plt.scatter(flow,height500,c=height500,marker='o',cmap=cm.Reds,label='500start',vmin=20,vmax=28)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Relatively flow',fontsize=15)
plt.ylabel('Peak-height(%)',fontsize=15)
plt.ylim(20,28)
plt.suptitle('Population mobility & Peak-height',fontsize=15)
plt.show()

plt.subplot(2,2,1)
plt.scatter(dense,acc,c=acc,marker='o',cmap=cm.Reds,label='50start',vmin=88,vmax=95)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Population density(people/km^2)',fontsize=15)
plt.ylabel('Infect rate(%)',fontsize=15)
plt.ylim(88,95)
plt.subplot(2,2,2)
plt.scatter(dense,acc150,c=acc150,marker='o',cmap=cm.Reds,label='150start',vmin=88,vmax=95)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Population density(people/km^2)',fontsize=15)
plt.ylabel('Infect rate(%)',fontsize=15)
plt.ylim(88,95)
plt.subplot(2,2,3)
plt.scatter(dense,acc300,c=acc300,marker='o',cmap=cm.Reds,label='300start',vmin=88,vmax=95)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Population density(people/km^2)',fontsize=15)
plt.ylabel('Infect rate(%)',fontsize=15)
plt.ylim(88,95)
plt.subplot(2,2,4)
plt.scatter(dense,acc500,c=acc500,marker='o',cmap=cm.Reds,label='500start',vmin=88,vmax=95)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Population density(people/km^2)',fontsize=15)
plt.ylabel('Infect rate(%)',fontsize=15)
plt.ylim(88,95)
plt.suptitle('Population density & Total infect rate after 1year',fontsize=15)
plt.show()

plt.subplot(2,2,1)
plt.scatter(flow,acc,c=acc,marker='o',cmap=cm.Reds,label='50start',vmin=88,vmax=95)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Relatively flow',fontsize=15)
plt.ylabel('Infect rate(%)',fontsize=15)
plt.ylim(88,95)
plt.subplot(2,2,2)
plt.scatter(flow,acc150,c=acc150,marker='o',cmap=cm.Reds,label='150start',vmin=88,vmax=95)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Relatively flow',fontsize=15)
plt.ylabel('Infect rate(%)',fontsize=15)
plt.ylim(88,95)
plt.subplot(2,2,3)
plt.scatter(flow,acc300,c=acc300,marker='o',cmap=cm.Reds,label='300start',vmin=88,vmax=95)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Relatively flow',fontsize=15)
plt.ylabel('Infect rate(%)',fontsize=15)
plt.ylim(88,95)
plt.subplot(2,2,4)
plt.scatter(flow,acc500,c=acc500,marker='o',cmap=cm.Reds,label='500start',vmin=88,vmax=95)
plt.grid()
plt.colorbar()
plt.legend()
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.xlabel('Relatively flow',fontsize=15)
plt.ylabel('Infect rate(%)',fontsize=15)
plt.ylim(88,95)
plt.suptitle('Population mobility & Total infect rate after 1year',fontsize=15)
plt.show()